### ISSUE TITLE
Please, please provide *decent* installation instructions

### ISSUE THREAD

**Issue by rgpublic** [mozilla/send#1356]
Dear Mozillas, why is this so *incredibly* difficult to setup (at least for someone not literally living in the NodeJS universe)? Do y'all really *want* us to run this stand-alone? Or is this another way of saying: Please don't try this at home? 

You have docker containers and all this other fancy modern stuff so getting this running with all dependent services should be a breeze, right? Unfortunately: No :-(
The installation instructions start with talking about an "ephemeral development server". Um, nope, I don't want that. Then there is somewhat hidden a page called "Build". But if you follow the instructions there you run into all sorts of errors. And then I realize I need a Redis server. Ummm, I don't have one of course. So, perhaps a docker image would be better. I try that... More errors. So I wonder: Just plain and simple now... What is the *easiest* way to get this up and running if I just have a simple run-of-the-mill Ubuntu root server? I'm not interested in studying all the mumbo-jumbo about npm, nodejs, webpack, docker, redis whatever. Just tell me for such a plain server: Which packages do I need to install? What do I need to run?

**Comment by oliver-dvorski** [comment]
I'll just start with apologising for the fact that this reply probably isn't going to help you at all. Then I'd like to ask if you're trying to set up a dev environment or if you want to run this on some production machine?

If you'd like to get it up and running on a dev env, the only caveat I've found is that you _need_ to be using node 10.x for the npm installation to go through. Node 12 won't work because one of the dependencies simply won't compile or smth, drove me mad.

If you're trying to run this in production... tough luck, I guess? I'm still trying to figure out how exactly this thing works but hey, at least it's a fun way of learning new stuff. If you're offended by that last remark, please remember that nobody owes you a manual here. Docs would be great but writing those takes time, which costs money and sometimes there's just more important things that need to get done before a proper wiki can be written. Eather way - gl, hf

**Comment by zerohashcrbn** [comment]
Hey buddy @rgpublic  I'm extremely agree with you and I've already suffered your pain longtime ago. There are certain things that are published in GitHub that developers are not sharing for the common use but for fulfilling the "open-source quote". I recommend you instead to figure out how to run properly "Firefox Send", to take a look on https://www.projectsend.org/. It's quite easy to install and do exactly the same. Even you can run it in a simple Raspberry Pi3 without major issues. Cheers.

**Comment by rgpublic** [comment]
Hey, @zerohashcrbn thanks for the tip, but we are already running ProjectSend here in our company, but I'm not too happy with it either. That's why I wanted to try out Firefox Send. ProjectSend is quite a hassle if you have lots of different and always changing people to communicate with. Users, downloads, etc pile up, are not auto-cleaned etc. All in all, yes, it does the job but is IMHO rather complex. I'm looking for sth. way simpler where I can just upload a file, get a URL out with end-to-end-encryption. Firefox Send could fit in here beautifully, but sadly it's a total mess to set this up. And I have a hunch that this doesn't have to be the case. The install process is probably not really complex by itself, but it's just the terrible docs which thwart any attempt to get this thing set-up. I only don't know whether this is *intentional*, but the docs are so ridiculously bad that I can't imagine it being an accident.

**Comment by zerohashcrbn** [comment]
@rgpublic Understood. Look at this https://github.com/Kickball/awesome-selfhosted#single-clickdrag-n-drop-upload... There is a project called Jirafeau, looks quite good https://gitlab.com/mojo42/Jirafeau.

**Comment by oliver-dvorski** [comment]
This got me interested. Figured it can't be **that** difficult... Got it up and running on https://send.oliverdvorski.com/ in less than 10 minutes. If you actually care about the _how_ of the deployment process, notice what it says under `/docs/build.md` - you're supposed to run `npm run build` to build the assets and then set up a server with `npm run prod`. To deploy it to my VPS I just ran the build command and ran `npm run prod` as a daemon. After that, I had to make nginx work with this config so I've set up a reverse proxy that allowed me to access the express server created by the daemon through port 80. Here's a tutorial on that https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-14-04 (under the heading "Set Up Reverse Proxy Server")

As far as I understand, this still doesn't store the files on my hardware, there's some additional configuration required for that but honestly, I just wanted to get this running out of spite so this is where I'll end my experimentation for today.

**Comment by rgpublic** [comment]
Thanks, but no luck:

![grafik](https://user-images.githubusercontent.com/17726950/60531672-cbb6f400-9cfb-11e9-9b54-dc3e5ba8ffc1.png)

**Comment by oliver-dvorski** [comment]
😬 ouch. My bad. `npm install` has to be run after cloning

**Comment by rgpublic** [comment]
Okay, one step further. Next error. At least you see now: The docs could definitively be improved ;-) And remember: All this stuff might very well be ridiculously easy to solve if you are used to NodeJS and npm etc. If this was a PHP application, for example, I probably would be able to solve even rather obscure problems. But if you are not normally working with this kind of stuff, even minor mistakes in the docs can cause major headaches :-(

![grafik](https://user-images.githubusercontent.com/17726950/60532410-885d8500-9cfd-11e9-92a6-ae35e2d4a841.png)

**Comment by oliver-dvorski** [comment]
Strange. What npm and node  versions are you running?

**Comment by rgpublic** [comment]
* "npm -v" prints "5.8.0"
* "node -v" prints "v8.11.4"
I'm on Ubuntu 18.10 (cosmic)

**Comment by oliver-dvorski** [comment]
Ok, try updating to node 10. I'll see if I can reproduce this on node 8 in
a bit. After the update, run `rm -rf node_modules` to be on the safe side
and run `npm install`, maybe that could help

rgpublic <notifications@github.com> schrieb am Mi., 3. Juli 2019, 15:36:

**Comment by rgpublic** [comment]
Okay. This took a while, because our server is S-L-O-W. Nevertheless, I've updated the whole server from Ubuntu Cosmic to Ubuntu Disco which fortunately brings Node 10:
* "npm -v" prints "5.8.0"
* "node -v" prints "v10.15.2"
Still it aborts on exactly the same error, though (Cannot find module webcrypto_core). In addition there's now a new warning above saying "npm WARN npm does not support Node.js v10.15.2" but I think I can ignore that, right? At least these are the versions that come with the distro so I wouldn't really know how to change that anyway :-/ npm seems to work as usual, though...

**Comment by oliver-dvorski** [comment]
https://stackoverflow.com/questions/47226238/npm-warn-npm-npm-does-not-support-node-js-v9-1-0

After a bit of research, I got the impression that npm 5.8.0 should work with node 10.something. I could be wrong tho. Either way, I never ran node or npm from ubuntus repos. I'd try installing it the official way. When I downgrade to Node 10, I still use npm 6.9.0 and I still don't have that issue. Again, try removing node and installing it like described here: https://github.com/nodesource/distributions/blob/master/README.md#debinstall

Just make sure to use version 10.x

And then the `rm -rf node_modules && npm install && npm run build` sequence **should** work

**Comment by rgpublic** [comment]
Okay, I uninstalled nodejs packages from Ubuntu, did the install from the manual and now "npm install" hangs on "Downloading chromium" at 35%. Good grief, this is one of the worst installations I've ever encountered. But thanks a lot for your help @oliver-dvorski. I will definitively need some rest over the weekend and try again on Monday.

**Comment by oliver-dvorski** [comment]
Downloading chromium? 🤔 I don't really see why npm would be downloading
chromium for this project. Anyway, have fun over the weekend, I'll be here
on Monday 😊 try screenshoting the process for me then if you don't mind.
So I can try to reproduce the error

rgpublic <notifications@github.com> schrieb am Do., 4. Juli 2019, 17:14:

**Comment by rgpublic** [comment]
@oliver-dvorski Okay, new week, new luck. I've switched to a large server, because I think the server had to little memory for whatever "npm install" is doing. This is why the "downloading chromium" got stuck. Now, on the new server I installed Node 10 from the Node Source Repository, then "npm install" which finished with no problems and the "npm run build". Still the same error, though:

![grafik](https://user-images.githubusercontent.com/17726950/60805331-0e575100-a180-11e9-8e5d-54d84474807e.png)

**Comment by oliver-dvorski** [comment]
Spun up a vm to reproduce this. I was indeed able to. Then I did Googled that error and the only result solved it fantastically - https://github.com/mozilla/send/issues/1221#issuecomment-474449798

Running things as root isn't recommended anyway, I didn't even notice that in the screenshots lol

**Comment by rgpublic** [comment]
Wow. Incredible. It worked. Thank you so much @oliver-dvorski. Weird, when I google that error it doesn't turn up anything valuable. Terrible personalized results :-( Note for others: After switching to the new user you need to do the "rm -rf node_modules", "npm install" from the new user account again. It isn't sufficient to just do the "npm run build" again with the new user or you will run into that error again.

Next I should run "npm run prod" right? How did you run this "as a daemon"? Just adding "&" or "nohup"? Of course I want to run this permanently. And then it runs on some exotic port I assume and I will have to set up my apache to do reverse proxying to finally (hopefully) see the page, correct?

**Comment by oliver-dvorski** [comment]
Precisely. You can set up the daemon with PM2, like described in the tutorial I linked earlier (https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-14-04#manage-application-with-pm2).

Let me know if you managed to set it up, I'd love to see it :)

Also, are you going to configure your own storage situation?

**Comment by rgpublic** [comment]
Wohoo. It finally works. It will be a non-public server, so I cannot give you a link or anything, I'm afraid. Only thing that spoils the final party is the fact that the generated URLs are all of the form: http://127.0.0.1:1443/....
i.e. the proxied connection not the external one. If you also know any way around that @oliver-dvorski I would be very happy to learn about it :-)

Anyway, I'd like to share some information/summarization for other poor souls that end up here to find out how this thing is *really* installed:

* git clone https://github.com/mozilla/send.git htdocs
* Make sure you are NOT root (e.g. "su www-data" or whoever is usually the owner of your htdocs folder)
* npm install
* npm run build
* Create a file "run.sh" with:
```
#!/bin/bash
nohup su www-data -c "npm run prod" 2>/dev/null &
```
* chmod +x run.sh
* ./run.sh

Now the Send backend should be running on port 1443. You can check with:
* apt install telnet
* telnet localhost 1443

Next (assuming Apache webserver), do:
* a2enmod proxy
* a2enmod proxy_http
* a2enmod proxy_wstunnel

In your Apache virtual host, insert this:
```
    # If it's a normal file (e.g. PNG, CSS) just return it
    RewriteCond %{REQUEST_FILENAME} -f
    RewriteRule .* - [L]

    # If it's a websocket connection, redirect it to a Send WS connection
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /(.*) ws://127.0.0.1:1443/$1 [P,L]

    # Otherwise redirect it to a normal HTTP connection
    RewriteRule ^/(.*)$ http://127.0.0.1:1443/$1 [P,QSA]
    ProxyPassReverse  "/" "http://127.0.0.1:1443"
```

Phew! What a nightmare. Thanks again, @oliver-dvorski . Never would have managed it without your help.

**Comment by oliver-dvorski** [comment]
No worries, happy to help

On my setup the URLs render as expected. So it could be your Apache config... I'm a bit clueless in that department tho. 

![Screenshot_20190710-124458_Firefox](https://user-images.githubusercontent.com/9038049/60963496-404bed00-a311-11e9-9204-f76e28c72d96.jpg)

**Comment by rgpublic** [comment]
I've updated my comment. "ProxyPreserveHost on" does the magic. Remaining problem (which I can see from your screenshot does also happen your setup): The generated URL is http://... I think this is quite problematic, because the URL can be intercepted when it is being sent unencrypted over the web, right? Anyone with access to the URL can download the file which kinda thwarts the original intention ;-) Still trying to find a good way around this...

**Comment by oliver-dvorski** [comment]
Excellent! Don't forget to close the issue 😉

I don't see how this would be horrific? The only way I see this data being intercepted is if you would catch someone visiting that http link. I understand that no computer system can be trusted but that's your LAN we're talking about. Uploading some shady stuff at work? 😜 You can use a VPN which protects against this and you can password protect that file/archive for additional piece of mind.

The weird thing is that this isn't happening on my installation any more... Odd. If it persists, you might want to open up a new issue 😁
![Screenshot_20190710-210502_Firefox](https://user-images.githubusercontent.com/9038049/60997712-bffcaa80-a357-11e9-8327-3c74980e1a32.jpg)

**Comment by rgpublic** [comment]
Hahaha, @oliver-dvorski , nope - don't have any shady stuff here to upload, but thinking about it you are giving me new ideas ;-) No, generally, we plan to use it the other way round: We give customers the credentials to the server and they can send *us* some secret documents etc. And in this context, the URL is transmitted unencrypted over the internet if you don't watch out and use HTTPS. The screenshot you gave is from send.firefox.com, though, not your own server - so perhaps it isn't really fixed for your server as well. Anyway, I think I can close this bug and if I cannot sort out the protocol issue, I might file a new bug - just as you proposed - for this issue specifically.

**Comment by fzzzy** [comment]
@rgpublic Before you close this bug, could you put the information in https://github.com/mozilla/send/issues/1356#issuecomment-510008889 into a deployment.md file in the docs directory, link to it from the README.md, and open a pull request?

Thanks!

**Comment by rgpublic** [comment]
Sure, @fzzzy Will try to do this. BTW: I just solved the final protocol problem by finding this issue:
https://github.com/mozilla/send/issues/1238
You have to set environment variable NODE_ENV=production 
I edited my comment / startup script accordingly.

**Comment by oliver-dvorski** [comment]
Welp, that's embarrassing 😬

Either way - good job!

**Comment by rgpublic** [comment]
Arrrgh. When I set NODE_ENV=production, the links are correctly generated as https://  but now all generated links are immediately expired. Gee, installing this thing is *annoying* like nothing else.

**Comment by rgpublic** [comment]
Ah, found the solution in another issue: https://github.com/mozilla/send/issues/1358
You should NOT use NODE_ENV=production but instead use:
RequestHeader set X-Forwarded-Proto https
Now, finally it really seems to work as it should. Sigh. Okay, I will once again edit my installation comment above and then put everything into a pull request.

**Comment by rgpublic** [comment]
Done. Wow. A bit exciting. My first pull request on GitHub ;-)
https://github.com/mozilla/send/pull/1366

**Comment by zerohashcrbn** [comment]
@oliver-dvorski @rgpublic Hey guys, after reading your fantastic exchange of ideas, no just to be curious I installed firefox send self-hosted, however I'm facing an issue that I don't understand properly. Each time I upload a file, immediately the link expires. I researching but I'm not able to find a clue about where the problem is. I'm using Nginx as reverse proxy, I don't know if perhaps it works better with Apache instead. 

BTW sorry for writing in a "closed issue". 

If you want to take a look and to reproduce my problem, please click on this. https://send.openrandomsolutions.org

Cheers.

**Comment by rgpublic** [comment]
@zerohashcrbn Did you read my note about "NODE_ENV=production"? The same problem occured when I ran with "NODE_ENV=production". Make sure neither your run.sh includes that line nor your normal environment (you could check with "export" AFAIK).

**Comment by zerohashcrbn** [comment]
@rgpublic Yes, I read it, however I'm keep facing the issue, even I included the RequestHeader set X-Forwarded-Proto https in my Nginx VirtualHost and the problem persist. Well thank you very much, I'm gonna keep researching, at the end I'm just intalling it for testing purposes, is not a big deal. 

Cheers.
