### ISSUE TITLE
When first navigating to the Send page expired files are still displayed on it after 24 hours, until the page is refreshed

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#200]
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Use a nightly profile where you have a file uploaded 24 hours ago.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to https://send.dev.mozaws.net/.
2. Observe the bottom part of the page.

[Expected result]:
- Only files which are not yet expired are displayed.

[Actual results]:
- Expired files are displayed.

[Notes]:
- Not sure if the issue is reproducible on Mac or on the stage page, but I'll test this and update the issue accordingly.
- Here is a screen recording with the issue:
![screenshot from 2017-07-14 16_58_52](https://user-images.githubusercontent.com/18304511/28216035-c07ddc94-68b8-11e7-884c-6fbe449e3907.png)

**Comment by dannycoates** [comment]
I can't repro this on dev. @dnarcese can you confirm this is fixed?

**Comment by ericawright** [comment]
we were looking at that this morning and are unsure. Locally if you change the expiry on the front to a really short time it does repro, but we didn't look deep enough to figure if that was because the file was not actually removed from the backend.

**Comment by dannycoates** [comment]
Thanks @ericawright, closing as fixed. #297 fixes the server side.

**Comment by SoftVision-CiprianMuresan** [comment]
I was still able to reproduce this issue on Mac and Windows this morning.
![still reproducible](https://user-images.githubusercontent.com/18304511/28573107-2aefd73e-7152-11e7-810e-78b5c333b0ff.png)
<img width="1280" alt="screen shot 2017-07-25 at 11 58 32" src="https://user-images.githubusercontent.com/18304511/28573108-2cc8403c-7152-11e7-8431-92eef40502ab.png">

 I'll leave it closed until I recheck this tomorrow morning.
