### ISSUE TITLE
en-US send.ftl file has duplicate messages

### ISSUE THREAD

**Issue by Pike** [mozilla/send#335]
```shell
compare-locales l10n.toml . en-US
en-US/send.ftl
    WARNING: copyUrlHover occurs 2 times
    WARNING: deleteButtonHover occurs 2 times
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times
```

The duplicated entries should be removed.

CC @flodolo @mathjazz @TheoChevalier

**Comment by flodolo** [comment]
Fixing.

**Comment by pdehaan** [comment]
Wow, that `compare-locales` is pretty awesome.
What'd be the best place to file an enhancement request? It seems like even if I get a "WARNING" or "ERROR" it still exits with a status code of 0.

```sh
$ compare-locales l10n.toml . en-US fr de

de/send.ftl
    WARNING: copyUrlHover occurs 2 times
    WARNING: deleteButtonHover occurs 2 times
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times
    ERROR: Missing value at line 10, column 1 for uploadPageBrowseButton
    ERROR: Missing attribute: title at line 35, column 1 for deleteFileButton

en-US/send.ftl
    WARNING: copyUrlHover occurs 2 times
    WARNING: deleteButtonHover occurs 2 times
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times

fr/send.ftl
    // add and localize this file

de:
changed: 64
changed_w: 384
errors: 4
unchanged: 4
unchanged_w: 6
warnings: 2
94% of entries changed

en-US:
errors: 2
unchanged: 68
unchanged_w: 390
warnings: 2
0% of entries changed

fr:
missingInFiles: 70
missing_w: 393
0% of entries changed


$ echo $? # 0
```

I was thinking it may be nice to try running compare-locales in CI as part of our linting (although not sure how challenging it'd be to install via `easy_install` on Circle-CI).

**Comment by flodolo** [comment]
@pdehaan I'm pretty sure you're looking at an old version of the repo.

There are warning about duplicated strings in locales, but we should be able to ignore them (first update to the file will clean them up). I fixed all other errors.

**Comment by pdehaan** [comment]
@flodolo Yeah, sorry, I didn't sync to master since I wanted to check the error codes. I was just commenting on how having a non-zero status code from `compare-locales` would be useful since it'd fail builds on any errors.

**Comment by flodolo** [comment]
If we want to run it on automation, I can also clean up the locales from error.

**Comment by Pike** [comment]
Filed [bug 1384981](https://bugzilla.mozilla.org/show_bug.cgi?id=1384981) on the shell error code. I think we should only error on ERROR, and warnings should be a 0.

**Comment by pdehaan** [comment]
@Pike Agreed. Thanks!

---

Speaking of duplicate entries, I think we still have a few. I can take a look at @flodolo's PR and try fixing for the rest:

```sh
$ compare-locales l10n.toml . `ls public/locales`

cs/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times

cy/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times

de/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times

dsb/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times

el/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times
    +...

es-AR/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times
    +...

es-ES/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times

fr/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times

fy-NL/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times

hsb/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times

hu/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times

it/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times

ja/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times

kab/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times

ms/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times

nb-NO/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times
    +...

nn-NO/send.ftl
    +...

pt-BR/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times

pt-PT/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times

sk/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times

sl/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times

sv-SE/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times

tr/send.ftl
    +...

zh-CN/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times

zh-TW/send.ftl
    ERROR: copyUrlHover occurs 2 times
    ERROR: deleteButtonHover occurs 2 times
```

**Comment by flodolo** [comment]
> There are warning about duplicated strings in locales, but we should be able to ignore them

OK, let me fix those and ask you for review ;-)
